services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
     - DOMAIN=${DOMAIN}
     - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
     - ADMIN_TOKEN=${ADMIN_TOKEN}
    volumes:
      - ${VW_FOLDER}:/data
    networks:
      - reverse-proxy
    # Reverse-Proxy nutzen.
    # ports:
    #   - 80:80

# Nutze NFS-Volume auf meinem TrueNas 
volumes:
  vw-data:
    driver: local
    driver_opts:
      device: ":/mnt/pool/nfs/docker-volumes/vaultwarden"
      type: "nfs"
      o: "addr=192.168.178.135,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"



# Nutze den Reverse-Proxy.
networks:
  reverse-proxy:
    external: true
