services:
  glance:
    container_name: glance
    labels:
      glance.name: Glance
      glance.icon: di:glance
      glance.url: https://home.felix0351.duckdns.org
      glance.description: Dashboard
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - reverse-proxy
    env_file: .env

networks:
  reverse-proxy:
    external: true
